### ISSUE TITLE
Collector doesn't support Postgres9.3

### ISSUE THREAD

**Issue by selwyni** [cmu-db/ottertune#100]
pg_stat_archiver statistics collector didn't come to PostgreSQL till 9.4. As a result, collecting data fails.

We should add some way to check versions of the DBMS in the collector before looking for stat views that don't exist yet.

**Comment by selwyni** [comment]
<img width="1250" alt="screen shot 2018-02-23 at 2 11 40 pm" src="https://user-images.githubusercontent.com/18583496/36612378-7495f3ce-18a4-11e8-99c3-97b6e0791be9.png">

psql raises an exception, and the collector stops. Bohan and I are getting around it by temporarily removing the pg_stat_archiver from the list of tables to collect statistics from for now. I don't know if there are other options besides ignore the missing tables in a particular Postgres version.

**Comment by bohanjason** [comment]
Fixed #111
