### ISSUE TITLE
Change Celery log path 

### ISSUE THREAD

**Issue by bohanjason** [cmu-db/ottertune#102]
Celery and Django have the same log file website.log, it may cause some permission issues when restarting Celery worker or Django.   For now we can grant permissions for /tmp/log/website.log* on ottertune machine when encountering such problem. It is not urgent, and I will change the Celery log file to celery.log when I am free.

**Comment by apavlo** [comment]
We should use `/var/log/ottertune/` or `/var/log/apache/ottertune/`. If we use `/tmp`, then we will lose all the files when the server restarts.

**Comment by bohanjason** [comment]
Thanks ! Log files are located in /var/log/ottertune/ now.
