### ISSUE TITLE
How to install ottertue?

### ISSUE THREAD

**Issue by junli0411** [cmu-db/ottertune#106]
Hi,
Is there any document for the full installation ? is the website already included in the ottertune ?
Thanks

**Comment by apavlo** [comment]
Instructions are coming soon. This repo contains everything needed to run the complete system.

**Comment by xiaoyuaner** [comment]
When do we have instructions~ I am still waiting for this. ^_^

**Comment by enjoy988** [comment]
Anyone is using OtterTune now? Would really appreciate if we can exchange the experiences of using it.

**Comment by kylechenoO** [comment]
I want to test it, but can not install it while initial django database, something error in the hard code.
 
 
 
------------------ Original ------------------
