### ISSUE TITLE
move parameters to the constant file

### ISSUE THREAD

**Issue by bohanjason** [cmu-db/ottertune#136]
Move the parameters in the analysis part to the constant file. ottertune/server/website/website/settings/constants.py

Tune these parameters if you have free time.

**Comment by swimj** [comment]
I wonder if it would be better to make a separate constants file for the analysis directory? 

Otherwise, the import path will have to be something like,
"from ..website.website.settings import constants" which feels convoluted.

And I think the pure analysis code should be relatively independent of the website code.

**Comment by bohanjason** [comment]
I think we only need to import the constants in the task files like this line. Pass the parameters into the analysis part instead of importing the parameters into analysis files directly.  Any ideas ? 
https://github.com/cmu-db/ottertune/blob/490a9d5aa117904cec3ee39dae7d8ddd078a0c51/server/website/website/tasks/async_tasks.py#L307

**Comment by selwyni** [comment]
https://github.com/cmu-db/ottertune/blob/490a9d5aa117904cec3ee39dae7d8ddd078a0c51/server/analysis/constraints.py#L125
That works for some, but here's an exception - a constant in an analysis file. 
It was the only one I found so it could just be left alone, or tuned at some other point

**Comment by bohanjason** [comment]
Thanks Jacky !  I think we can revise the function to pass that parameter in. e.g. change the function https://github.com/cmu-db/ottertune/blob/490a9d5aa117904cec3ee39dae7d8ddd078a0c51/server/analysis/constraints.py#L113
to : 
def randomize_categorical_features(self, sample, p = 0.3, scaled=True, rescale=True): 

I still think passing these parameters into the function is a right way, which is more flexible to change parameters in the future tuning.

**Comment by swimj** [comment]
@selwyni , do you have stuff for this? Maybe we had a miscommunication but for some reason I thought you'd started on this, so I was waiting for you. If not, just let me know, so I can do this for Bohan.

**Comment by bohanjason** [comment]
Hi Justin,  I think Jacky is working with Shuli on the controller. Could you please help move the parameters?  I need this part to tune OtterTune's hyper-parameters.  Thanks a lot !

**Comment by swimj** [comment]
I'm doing it now

**Comment by swimj** [comment]
I can't send in a PR because I haven't switched my local system to Python3 yet, so can't run all the tests and can't run the style validator.

For now, I've sent you an email, @bohanjason , with the files you should need.  I'll try to also work on issue #143 since I need to use Vagrant to develop.
