### ISSUE TITLE
Tuner not running

### ISSUE THREAD

**Issue by lukasmichel** [cmu-db/ottertune#161]
I am trying to test ottertune on my local machine. I was able to create a server as described in the wiki. I then was able to refactor the fabfile located in ottertune/client/driver so that it runs on my machine. So, I monitor a workload execution, upload the results of that monitoring and then run the query-and-get.py script. But I do not get any results from the tuner. I ran the query-and-get.py script for 12 hours and I never received a result or at least a "tuning failed" message. The status of the upload on the website is "UNAVAILABLE". 
What do I have to do to get the tuner running?

**Comment by apavlo** [comment]
@bohanjason Can you look into this?

@lukasmichel It may just be easier for you to use our service running at CMU.

**Comment by lukasmichel** [comment]
I tried using the ottertune server at ottertune.cs.cmu.edu a few hours ago, but the tuning failed during the workload mapping with the following reason:
```
Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 240, in trace_task R = retval = fun(*args, **kwargs) File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 438, in __protected_call__ return self.run(*args, **kwargs) File "/var/www/ottertune/server/website/website/tasks/async_tasks.py", line 416, in map_workload assert len(unique_workloads) > 0 AssertionError 
```
I tried again just now, and now I get a Server Error (`Server Error (500)`) as answer from the server when uploading a result.

**Comment by lukasmichel** [comment]
Thank you, I did not start the celery worker like this. Now the tuner responds.
I have one more question: Is it sufficient to populate the repository by uploading data into a non-tuning session? And if yes, how many different workloads do I need to monitor how many times so that the tuner will have enough data to actually tune something?

**Comment by bohanjason** [comment]
The basic step is to upload the training data to the non-tuning session, then create a tuning session and upload tuning task. The server can make use of the training data in the non-tuning session to train ML models.  Be sure to run celery worker and celery beat before. 

The tuning result highly depends on your training data . The training data needs to be widely distributed in the search space. For example, if you have 1000 training results but their configs are all very similar, the ML model can only have a good prediction on that area which has enough data, but know little about the other regions. 

Also, it will be better if there exists some configs with good performance in your training data. Then our tuner is likely to search around that good config and recommend better.

In my experiment, I use 300 training data, and recommend a config which improves throughput from 400(default) to 3000. 

To get started, I recommend to use the same workload.  For example, if you want to recommend configs for the TPC-C benchmark on the client side, then collect the training data with the same TPC-C workload. 

We plan to write more documents, and provide our training data as a tuning sample.

**Comment by enjoy988** [comment]
Hi, according to this guide, I don't need to setup Vagrant and Virtualbox first before running the tuner?

**Comment by lukasmichel** [comment]
Thank you very much, @bohanjason , now the tuner is working. So I understand it right that, to work properly, ottertune needs to have seen a lot of different, quite well configurations to be able to tune those configurations even further.

**Comment by KhangxLi** [comment]
Hi, I keep getting Server Error (500) when I try to upload to locahost:8000/new_result, can anyone help?
