### ISSUE TITLE
Check if the workload name contains invalid characters

### ISSUE THREAD

**Issue by 11hifish** [cmu-db/ottertune#162]
Check if the workload name in the upload result summary files has invalid characters like '.', which will make the whole webpage down now.

**Comment by apavlo** [comment]
Is this the same problem as  #161?

**Comment by 11hifish** [comment]
It might not be the same problem. I tried to upload data collected from AWS. The upload script reports `stored successfully` and the web response is always 200 OK and does not cause any error. However, the website shows nothing after I uploaded the data. I found this is caused by timeline.js, which puts the workload name into a url but it does not recognize '.' in url.

**Comment by bohanjason** [comment]
One possible solution is to replace '.' with '_' for workload names when the tuner handles the uploaded files.  like this [line](https://github.com/cmu-db/ottertune/blob/1babeeb17e6ae033ddc179c4739fd071f1671821/server/website/website/views.py#L394)

**Comment by bohanjason** [comment]
Any update here ?  You can check the workload name on the server side https://github.com/cmu-db/ottertune/blob/1babeeb17e6ae033ddc179c4739fd071f1671821/server/website/website/views.py#L394. And return the error message if it fails. Workload name can only include numbers and '_'

**Comment by bohanjason** [comment]
Fixed. A valid workload name should only contain alpha-numeric, underscore(_) and hyphen(-)
