### ISSUE TITLE
Wiki Documents 

### ISSUE THREAD

**Issue by bohanjason** [cmu-db/ottertune#163]
We need more documents about installation and deployment. More detailed explanations on the controller, driver,  and tuner, etc .

**Comment by enjoy988** [comment]
Please provide detailed doc about how to use Ottertune to tune our actuall PostgreSQL, not just document about how to set up website to show fake data.

**Comment by KhangxLi** [comment]
Hi, I'm a first year student on my first internship trying to understand and make the software work with our databases. I would really like to see more how-tos and explanation documentation for the end user.

**Comment by dvanaken** [comment]
@bohanjason this was added, right?

**Comment by bohanjason** [comment]
@dvanaken Yes, it has an end-to-end example now.  But the document still needs to be improved.
