### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by enjoy988** [cmu-db/ottertune#164]
Hi,

When I tried to run 
python manage.py makemigrations website

According to this guid: 
https://github.com/cmu-db/ottertune/tree/master/server/website#6-start-the-message-broker-celery-worker-website-server-and-periodic-task

I got "Segmentatin fault" error

I am using CentOS6.6 with python3.6. 

Please help!

**Comment by apavlo** [comment]
Can you provide more information? Is there a stacktrace?
