### ISSUE TITLE
how could I run sample workload? (e.g. TPCH, TPCC)

### ISSUE THREAD

**Issue by jaesik817** [cmu-db/ottertune#166]
I want to run the ottertune for sample workloads (e.g. TPCH, TPCC),

however the workload on session info is empty.

How could I load(?) workload on ottertune page?

Thanks.

Best Regards, 

Jaesik Yoon.

**Comment by bohanjason** [comment]
There are two sides of OtterTune, server-side and [client-side](https://github.com/cmu-db/ottertune/wiki/client-side). When both sides are set up, you can run driver in the client side to  run a tuning loop. https://github.com/cmu-db/ottertune/blob/1babeeb17e6ae033ddc179c4739fd071f1671821/client/driver/fabfile.py#L178

**Comment by bohanjason** [comment]
Besides , we use OLTPBench to run workloads on the client side.
