### ISSUE TITLE
New URL for checkstyle.jar

### ISSUE THREAD

**Issue by xupefei** [cmu-db/ottertune#167]
https://github.com/cmu-db/ottertune/blob/1babeeb17e6ae033ddc179c4739fd071f1671821/client/controller/build.gradle#L79

They have moved the repo to Github. The download url is now `https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.8/checkstyle-8.8-all.jar`

**Comment by bohanjason** [comment]
Thanks!  It is fixed in PR #157
