### ISSUE TITLE
input_config.json file is missing

### ISSUE THREAD

**Issue by KhangxLi** [cmu-db/ottertune#168]
Hi, I'm trying to run gradle run as per ottertune/client/controller/read.me, but the config file input_config is nowhere to be found.

**Comment by bohanjason** [comment]
I think the sample config file is located at ottertune/client/controller/config/ .  You can use -f flag to specify the config file path .

Not sure about the default one.  @11hifish Could you please look into it ?

**Comment by KhangxLi** [comment]
Yes thanks, I've created a config file connecting to a database on a remote server so I don't really need the default one anymore (though it's still missing). Thanks

ps I'm trying to upload my generated data (knob json, etc.) and I keep getting server error 500. Do you know something about that @bohanjason? If not I'll open an issue tomorrow. :)

**Comment by ElviraSunshine** [comment]
@bohanjason Hi, I'm trying to run `gradle run -f XXX -t XXX` ,and now I get a Error : 

`FAILURE: Build failed with an exception.
* What went wrong:
 Problem configuring task :run from command line.
> Unknown command-line option '-f'.
`
Can you help me ?

**Comment by KhangxLi** [comment]
@ElviraSunshine go to ottertune/client/driver/fabfile.py to see the syntax in the task run_controller

**Comment by ElviraSunshine** [comment]
@KhangxLi Thanks.

**Comment by bohanjason** [comment]
I realize it is hardcoded previously. We fix it and currently you can set controller config path  "controller_config" in ottertune/client/driver/driver_config.  Thanks for reporting the issue.
