### ISSUE TITLE
How to get good training data

### ISSUE THREAD

**Issue by KhangxLi** [cmu-db/ottertune#171]
Hi, I get "WARNING: no training data, the config is generated randomly" from all of my tuning recommendation.
I have been uploading to a non-tuning session and to a tuning session. Is it because I have not yet enough data or because there is no data with good results?

What would the next step for me to make Ottertune stop generating random recommendations? Sorry if this is a problem on my side and not on Ottertune's side.

**Comment by bohanjason** [comment]
Hi, it's likely you have not started the periodic tasks. After uploading the training data, make sure the periodical tasks are executed at least one time. 
``
python3 manage.py celerybeat --verbosity=2 --loglevel=info 
``

Another possible reason is that your training data has different database versions or hardware types with the one you are tuning. Make sure your tuning session and non-tuning session have same database versions and hardware types.

Best,
Bohan

**Comment by KhangxLi** [comment]
Hi @bohanjason , I am definitely running the celerybeat. Both my tuning and training sessions have the same version and hardware type. 

I did need to modify the postgres-94_knobs.json in website/fixtures to match the min/max knob values of my 32 bit database. I am also tuning a postgres 9.5 while changing summary.json to 9.4 on every loop since 9.5 isn't working.

So I got to a point where I had about 50 training data when errors started happening. For example, in async_tasks.py at configuration_recommendation, when trying to get default knob values, it tries to convert string to float which doesn't work. Example knob: wal_sync_method's default is 'fdatasync', why convert to float?

Anyway, I will try to redo my experiments with a 64 bit postgres 9.3 since that's the one you said worked for you. Any advice or input is welcomed.

Thanks

**Comment by bohanjason** [comment]
As said in another PR #172,  the tuner will remove the duplicate knobs when tuning.

**Comment by thomasloubejac** [comment]
I also have the conversion issue with wal_sync_method, did you manage to fix this ?

**Comment by thomasloubejac** [comment]
I "fixed" it by setting it to not tunable in the fixtures and resetting the whole website
