### ISSUE TITLE
Optimal Training of ottertune - Tuner part

### ISSUE THREAD

**Issue by mayanktiwari09** [cmu-db/ottertune#172]
Initially we executed ottertune/client/driver>fabfile.py - run_loops with oltpbench - tpcc for a non-tuninig session (only upload data of fabfile was active). 

How we prepared the training data in non-tuning session:
- we ran fabfile run_loops for 50 iterations, and after every 50 iterations,  we randomly changed the knobs of postgres and changed the weights for transaction types in oltpbench/config/tpcc_config_postgres.xml. This was done only to create sparse training data. 
- finally we had a total of 600 points (in non-tuning session) as training data with 12 variations of different weights for transaction type (tpcc config). 
- Now after 600 points in non-tuning session, we created a tuning session. Again we started with fab file run_loops (tpcc with default weights for transaction type - 45,43,4,4,4). Now with each iteration, the tuner recommends a new settings which is applied to the postgresql, as of now there are around 500 points in tuning session. And still then the results of oltp-bench in results/ directory shows throughput as around 400 - 500 tps. This is the same as what we started. 

In the tuner, the background tasks were also running periodically along with async tasks hitting with every new point entry in server.  

As a whole we are confused with the number of training points in non-tuning session and tuning session, which will give a recommendation which increases the performance in tps for tpcc.

**Comment by KhangxLi** [comment]
Hi, do you get 'Warning, no training data, recommendation is random' or something similar and 'status: bad' in your next_config file?

**Comment by mayanktiwari09** [comment]
Hi KhangxLi, I think tuner is generating new configs, however it is not getting applied to the db. Please verify. I have seen usually this happens when tuner sees the same knobs. When I started giving random values in my postgres conf file, the training data size increases. As a whole I conclude, this may be happening, because the recommended configs (from tuner) are not getting applied to db. And the metrics collector fetches same knobs from db using 'show all' command. I would recommend for initial few iterations, try manually changing the postgres conf file > perform restart and in psql verify the changes using 'show all;'

**Comment by bohanjason** [comment]
Hi @mayanktiwari09 , sorry for the late reply. 

50 training data is not enough for tuning a config. To get started, I recommend to use a single workload with the same weights to try, and randomly generate 1000 configs for this workload to get training data.  Then use the training data to tune this workload. If it does not recommend a good config, let the tuner running for a long time (e.g one day) until it recommends a good one. If it works, we can try more workloads.

You also need to care about  min/max values of knobs. The tuner will try the knob within this range. Currently, we use default value as the minimum value,  and the maximum value of training data as the maximum value; For the memory-related knob like shared-buffer size, we use the memory of the EC2 instance type as the maximum value, which you choose at the tuning session.

As I said before, the performance highly depends on the training data, the data will also grow when you start the tuning loops. Currently, we just randomly generate the training data swept values of the knobs, maybe we will find a smarter way in future. 

Also, we will provide the training data for one or two specific instances soon to make users easy to get started. We hope users can see the performance improvement when using our provided training data.  

Best,
Bohan

**Comment by mayanktiwari09** [comment]
Hi @bohanjason thanks for your reply.

I did the setup as per your recommendation, I setup driver>fabfile.py to run for tpcc bench. Now TPCC has default weights 45,43,4,4,4. I ran a total of 15000 iterations from fabfile>run_loops where after each 15 iterations, I changed the knobs using bash scripts. At the end of 15000 iterations, I get a workload, with 1000 different knobs (training data size is now 1000). During the iterations we observer the throughput was around 400-500 tps.  

Now after this I ran the tuner session for a day, Here I observe that the during the tuning session, ottertune recommends configs for first few iterations, later it seems converging and keeps on recommending the same config, because of which we are still not able to get higher throughput apart from initial 400 tps.

Also I observe that the run_background_tasks whenever executes, gives the following warning
[2018-07-24 09:44:37,536: WARNING/MainProcess] /var/vcap/ottertune/server/analysis/cluster.py:454: RuntimeWarning: divide by zero encountered in log                                                       
  log_wks[indk] = np.log(model.cluster_inertia_ / (2.0 * K))   

Looks like either knob or metric purning is failing.

Can you advice if we need any more configurations for optimal tuning.

Thanks and Regards,
Mayank

**Comment by bohanjason** [comment]
Hi Mayank, Can you show the knobs OtterTune are recommending ? OtterTune should choose ten(default) knobs according to the training data and recommend values for these knobs. Let's see whether these knobs are good or not . Thanks.

**Comment by mayanktiwari09** [comment]
Hi @bohanjason,

Thanks a lot for your reply.

The last recommended knobs by ottertune is following:
{'recommendation': {'global.effective_cache_size': '6GB', 'global.max_worker_processes': 12, 'global.checkpoint_timeout': '11min', 'global.bgwriter_lru_multiplier': 9.0, 'global.maintenance_work_mem': '200MB', 'global.bgwriter_flush_after': '512kB', 'global.wal_buffers': '64MB', 'global.min_wal_size': '512MB', 'global.random_page_cost': 4.0, 'global.shared_buffers': '300MB'}, 'info': 'INFO: training data size is 905', 'status': 'good'}

after this, repeatedly the same knobs are getting recommended.

Thanks and Regards,
Mayank

**Comment by bohanjason** [comment]
Hey Mayank, The recommendation contains most knobs we want to tune except this knob  "checkpoint_segments" in postgres 9.3. Can you run the background task again to see the knobs ? Also check whether your training data and the preloaded knobs fixture have this knob. 

Thanks,

**Comment by mayanktiwari09** [comment]
Hi @bohanjason , thanks a lot for your reply and time.

While preparing the training data, we randomly sweep values of the following knobs:

shared_buffers 
effective_cache_size 
work_mem 
maintenance_work_mem 
bgwriter_lru_maxpages 
bgwriter_delay 
checkpoint_completion_target 
wal_buffers 
min_wal_size 
checkpoint_flush_after 
checkpoint_timeout 
effective_io_concurrency 
max_worker_processes 
bgwriter_flush_after 
bgwriter_lru_multiplier 
random_page_cost 

Are these knobs enough to prepare for training - postgresql 9.6 (should we add some more or remove any more.. as per your feedback, we will be removing checkpoint_segments). As per your feedback, we will again go for training using tpcc benchmark with its default configurations.

Need your advice.

**Comment by bohanjason** [comment]
Hi Mayank, Sorry for the confusion.  checkpoint_segments is  an important knob in Postgres 9.3, and you may want to include it.  I think this knob is deprecated in Postgres 9.6. 

I have not tried Postgres 9.6, but I have tuned Postgres 9.3 successfully. The knobs you listed and 'checkpoint_segments' should be enough for tuning Postgres 9.3.

**Comment by pritishmishra** [comment]
Hi @bohanjason 

Thanks a lot for taking time and looking into this issue. I am working on this along with @mayanktiwari09.

As you correctly mentioned, `checkpoint_segments` is deprecated for Postgres 9.6. From the documentation, I found the following suggestion.

```
Replace configuration parameter checkpoint_segments with min_wal_size and max_wal_size (Heikki Linnakangas)

If you previously adjusted checkpoint_segments, the following formula will give you an approximately equivalent setting:

max_wal_size = (3 * checkpoint_segments) * 16MB
```

We had used `min_wal_size` in our experiment's setup. We can repeat the experiment by including `max_wal_size` for sweeping the knobs.

Do you see any other issue in our setup, which we should rectify?

One last question, do you feel the Ottertune experiment setup should hold good for Postgres 9.6 too?

Thanks again for your help.
Regards
Pritish

**Comment by bohanjason** [comment]
Yes, By including max_wal_size,  I think you setup is good for tuning Postgres 9.6. Make sure you have swept some big values for the important knobs, because we use the max value of knobs in the training data as the max in the tuning range.
