### ISSUE TITLE
How to use the ottertune to tune mysql?

### ISSUE THREAD

**Issue by zhj4655** [cmu-db/ottertune#180]
Hi, how to use the ottertune to tune mysql? I find the server can only test on postgres.
When I create a new session on the website, it does not have the DBMS-mysql option.
Is there a way to test mysql using ottertune?
thanks

**Comment by bohanjason** [comment]
Hi,  

You may want to add MySQL database in the fixture ottertune/server/website/website/fixtures/dbms_catalog.json

The database type should be its id in  https://github.com/cmu-db/ottertune/blob/87c356655a4030123d4eec8b72453d4c12e49937/server/website/website/types.py#L33

Also, you should add knob and metrics fixture and preload them into the database.  e.g. The following are the fixtures for Postgres 9.3

ottertune/server/website/website/fixtures/postgres-93_knobs.json
ottertune/server/website/website/fixtures/postgres-93_metrics.json

Best,
Bohan

**Comment by zhj4655** [comment]
Thank you for your reply. I modified some files and now can run the ottertune to tune mysql, but I don`t have the knobs.json and metrics.json files. I creata them and add six knobs and two metrics into the two files, but the ottertune doesn`t work well. So I will be very grateful if you can give me a copy of the knobs and metrics files. By the way, what should I return of transaction_counter and latency_timer of mysql like  
https://github.com/cmu-db/ottertune/blob/87c356655a4030123d4eec8b72453d4c12e49937/server/website/website/parser/postgres.py#L68-L74
Thanks

**Comment by bohanjason** [comment]
You do not need find fixture for all metrics and knobs.  Get some important ones. 

The latency metric is incorrect here. We cannot find a metric to measure the latency in Postgres internal metrics.  See the recent PR #182 and its description , which supports to get the metric in the client side and upload it to the server. 

Find a similar metric to count the transaction in MySQL.  If you cannot find one, you may want to use the similar approach in that PR. OLTP-Bench should have some statistics about throughput and latency.

Best,
Bohan

**Comment by zhj4655** [comment]
OK, I will try again.
Thank you very much.

**Comment by bohanjason** [comment]
Hi, to make it easier to collect initial training data, we  add a session to randomly generated settings between min/max val. You may want to see the recent PR #184
