### ISSUE TITLE
fab upload_result says the /ottertune/output/*.json files are empty when they aren't

### ISSUE THREAD

**Issue by thomasloubejac** [cmu-db/ottertune#181]
this is where I am : 
`thomas@ubuntu:/ottertune_dev/ottertune/client/driver$ fab upload_result
[localhost] Executing task 'upload_result'
[localhost] local: python3 ../../server/website/script/upload/upload.py            ../controller/output/ ZZMS74VVXG6DQSXZNYH9 http://127.0.0.1:8000/new_result/

 b'{\n "start_time": 1539337711622,\n "end_time": 1539338058702,\n "observation_time": 347,\n "database_type": "postgres",\n "database_version": "9.6",\n "workload_name": "workload_name"\n}\n' 

b'New result form is not valid: <ul class="errorlist"><li>summary<ul class="errorlist"><li>The submitted file is empty.</li></ul></li></ul>'

Done.'`

I made the file /ottertune/server/website/script/upload/upload.py print the content of a json file in the controller/output/ directory and the content from the response and this is what I get.

I don't know what to do next, any suggestions ?

**Comment by bohanjason** [comment]
It seems that your uploaded files are not valid. Please double check the files in /ottertune/output/  , It should contain the files knobs.json, metrics_before.json, metrics_after.json, and summary.json.  Here is an example for Postgres:  ottertune/client/controller/sample_output/postgres/

**Comment by thomasloubejac** [comment]
thanks for answering.

I printed the raw string from the json file that's why it doesn't look correct but it actually is : 
```{
 "start_time": 1539765275861,
 "end_time": 1539765293098,
 "observation_time": 17,
 "database_type": "postgres",
 "database_version": "9.6",
 "workload_name": "workload_name"
}
```

the other json files were correct too.

I don't remember how but I managed to solve that problem,

The actual problem is that query_and_get either doesn't answer, or fails because of an empty answer from the server. (thus next_conf will always be empty)

here's what is printed : 
```
/driver$ fab get_result
[localhost] Executing task 'get_result'
[localhost] local: python3 ../../script/query_and_get.py http://127.0.0.1:8000 KR6P6CB5F9AK6F0C2ARO 5
Tuning failed

Elapsed time: 0.03973507881164551


Done.
```

**Comment by thomasloubejac** [comment]
I didn't touch files on the server side but I made a fresh install and it worked a little further. the problem is now the next_config generation

**Comment by molujii** [comment]
@thomasloubejac  how did you figure it out the problem of next_config generation
