### ISSUE TITLE
only works for MySQL?

### ISSUE THREAD

**Issue by harjots82** [cmu-db/ottertune#196]
Hi
does it work only for MySQL ? 
can it be used to tune Oracle ?

**Comment by apavlo** [comment]
@harjots82 We are working on Oracle now. It currently supports Postgres + MySQL.

**Comment by bohanjason** [comment]
You can extend OtterTune to your own target database, see FAQ wiki page. https://github.com/cmu-db/ottertune/wiki/FAQ#2-how-to-tune-a-new-database-
