### ISSUE TITLE
deploy?

### ISSUE THREAD

**Issue by fiser321** [cmu-db/ottertune#2]
hi, Can you provide a detailed deployment document?
 It's best to use a database case to deploy and explain as you can, and tell us how to use it
thank you！！！

**Comment by berlincount** [comment]
I'd also love a complete end-to-end example on how a test setup for MySQL would look like, and expected to be used.

e.g. given a MySQL backup ready to be restored and a stream of example, real-life queries ready to be streamed to it, what kind of scaffolding or wrapping would need to be used to get the recommended configuration settings to be ported back to the actual production systems look like?

**Comment by dvanaken** [comment]
Thanks for your interest in OtterTune! I'll be back working on the [deployment code](https://github.com/oltpbenchmark/website.git) in a day or two. The code in this branch only contains the ML libraries that are used by the deployment code. That's where the deployment instructions will be located as well, once written.

**Comment by tomzhang** [comment]
any update for this info?

**Comment by azman0101** [comment]
Hello, I've made a Dockerfile and docker-compose.yml files to ease the running of https://github.com/oltpbenchmark/website.git

But I don't see how to "connect" it with this project.

**Comment by caoli5288** [comment]
https://github.com/oltpbenchmark/website/issues/15
Need help to connect to target database and start sampling.:)

**Comment by dvanaken** [comment]
Site is now under construction with more contributors. Please check back soon!
