### ISSUE TITLE
fab upload_result says "Exception at /new_result Cannot find objective function"

### ISSUE THREAD

**Issue by melodylaw** [cmu-db/ottertune#204]
i use following command to upload my result:
root@vm-ubuntu: fab upload_result
but an error is reported:

**Exception at /new_result/**
**Cannot find objective function**
**Request Method: 	POST
Request URL: 	http://myottertune_server_ip:8000/new_result/**
Django Version: 	1.10.1
Exception Type: 	Exception
Exception Value: 	Cannot find objective function
Exception Location: 	/usr/local/software/OtterTune/ottertune/server/website/website/parser/base.py in convert_dbms_metrics, line 178
Python Executable: 	/usr/bin/python
Python Version: 	3.5.2
Python Path: 	
['/usr/local/software/OtterTune/ottertune/server',
 '/usr/local/software/OtterTune/ottertune/server/website',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/var/www/ottertune',
 '/var/www/ottertune/website']

my result files is stored in ottertune/client/controller/output/:
-rw-r--r-- 1 root root 8095 Mar 29 15:50 knobs.json
-rw-r--r-- 1 root root 14977 Mar 29 15:50 metrics_after.json
-rw-r--r-- 1 root root 14607 Mar 29 15:50 metrics_before.json
-rw-r--r-- 1 root root 170 Mar 29 15:50 summary.json

i check all the relative configuration files, but i don't find the reason.
I don't know what to do next, any suggestions ?

**Comment by melodylaw** [comment]
my result files is stored in ottertune/client/controller/output/:
-rw-r--r--  1 root root  8095 Mar 29 15:50 knobs.json
-rw-r--r--  1 root root 14977 Mar 29 15:50 metrics_after.json
-rw-r--r--  1 root root 14607 Mar 29 15:50 metrics_before.json
-rw-r--r--  1 root root   170 Mar 29 15:50 summary.json

**Comment by dvanaken** [comment]
This issue should be fixed now.
