### ISSUE TITLE
How to set up incremental knobs?

### ISSUE THREAD

**Issue by neonadia** [cmu-db/ottertune#215]
I would like to know if this function already exist, because accoding to your paper it is much better to use incremental knobs than a certain number of knobs.
Also I would like to know how to check the knob importance?

**Comment by arifiorino** [comment]
We are in development, and we're making much more knob configuration available to the user.

**Comment by neonadia** [comment]
Thank you for your reply. I found a closed pull "Add incremental knobs", it seems working fine for PSQL.

**Comment by dvanaken** [comment]
Currently a feature request. See #144
