### ISSUE TITLE
Travis CI: use Docker in builds

### ISSUE THREAD

**Issue by dvanaken** [cmu-db/ottertune#222]
Update .travis.yml to run tests using our Docker images: https://github.com/cmu-db/ottertune/tree/master/docker

I'm not sure of the best way to do this but it seems like the following needs to happen:
- Test the code in the repo pointed to by $TRAVIS_BUILD_DIR instead of cloning the repo: https://github.com/cmu-db/ottertune/blob/master/docker/Dockerfile#L12
- Use docker-compose to run the same tests we run in our current version of .travis.yml: https://github.com/cmu-db/ottertune/blob/master/.travis.yml#L46

**Comment by dvanaken** [comment]
@eribeiro Would you be able to work on this?

**Comment by edwardoliveira** [comment]
@dvanaken sure, I can take a stab at this. :+1: 

In fact, cloning the repo is not a best practice, but I left so that it didn't change very much from the previous Dockefile version.

**Comment by dvanaken** [comment]
@eribeiro @edwardoliveira It turns out I need this sooner than I thought so I'm working it now, but if you have time to review the PR tonight that would be helpful. I am planning to merge it tonight after I get #211 merged.

**Comment by edwardoliveira** [comment]
Sure! I can review it tonight.

**Comment by eribeiro** [comment]
You certainly know this, but to integrate into a travis-ci pipeline you probably need to make the changes in the diff below (see if helps, please):

[dockerfile.txt](https://github.com/cmu-db/ottertune/files/3448958/dockerfile.txt)

It moves back Dockerfile and docker-compose.yml to previous dir and change lines in Dockerfile accordingly.

PS: @edwardoliveira is my other GH account (long history...)

**Comment by edwardoliveira** [comment]
@dvanaken Hi, I have taken a first stab at using Docker for CI, but as you need this sooner (and I am reviewing a book for Manning whose deadline is tomorrow :grimacing: ), then you could take a look and see if there's anything worth including in your solution. Please, let me know what do you think. :)

**Comment by dvanaken** [comment]
@edwardoliveira Thanks for the head start! I will let you know when I submit a PR with the full changes.

**Comment by dvanaken** [comment]
Fixed in #224
