### ISSUE TITLE
unique hardware id 

### ISSUE THREAD

**Issue by bohanjason** [cmu-db/ottertune#230]
If two hardwares have same cpu, memory and disk, they should be same  hardware and have same (unique) hardware id. Now they have different hardware ids.

My concern is that it will affect the workload mapping phase, and the data cannot be reused even for same hardware.

**Comment by arifiorino** [comment]
We talked about this on Friday, I'll make the hardware table only have unique rows. Before adding a new hardware it will check if one exists.
