### ISSUE TITLE
Custom target objectives

### ISSUE THREAD

**Issue by dvanaken** [cmu-db/ottertune#243]
Add support for custom target objectives. The standard list of target objectives (currently throughput_txn_per_sec) should be extensible so that database- and user-specific can be registered with minimal effort.

**Comment by bohanjason** [comment]
I added this for latency target objective.  Refer to this PR  #182
The general idea is to get the metric from the client side and write it to metric_before and metric_after.
It may still need to be improved to make it easier to use.

**Comment by dvanaken** [comment]
Added in #253
