### ISSUE TITLE
Push ottertune official docker images for DockerHub

### ISSUE THREAD

**Issue by eribeiro** [cmu-db/ottertune#304]
Please, push official ottertune images on [DockerHub](https://hub.docker.com/) that docker-compose.yml can just pull it from there (no need to build). I have found this one: https://hub.docker.com/r/arifiorino/ottertune-server but it's not official.

It would be nice to have a cmu-db account with ottertune as one of the projects. You could provide latest (for each commit) as well as versioned images.

**Comment by apavlo** [comment]
We agree but we're not there yet.
