### ISSUE TITLE
Knob comparison improvements

### ISSUE THREAD

**Issue by dvanaken** [cmu-db/ottertune#309]
In the knob comparison view:
(1) use human-readable values. For example: 3000000000 --> 3 GB
(2) show the target objective for the experiment selected and the one being compared, and in the drop-down selection list

@arifiorino we can talk about this more tomorrow

**Comment by arifiorino** [comment]
This is fixed in #317 .

**Comment by dvanaken** [comment]
(2) Fixed in #319

**Comment by dvanaken** [comment]
(1) Fixed in #331
