### ISSUE TITLE
running experiment never getting completed

### ISSUE THREAD

**Issue by molujii** [cmu-db/ottertune#324]
![2a8b95ed-43ec-4ef6-b6f0-0d86ff797b1d](https://user-images.githubusercontent.com/37249180/71484061-7e41bc80-2830-11ea-8781-7b7b17c9f062.jpg)

**Comment by apavlo** [comment]
This screenshot is not helpful. Can you provide additional information?

**Comment by molujii** [comment]
@apavlo  when i am running "fab run_loops:10"  the first collection of metrics is done after that 
starting experiment is running forever i think so that the experiment is not running and aslo it is not showing any error .

**Comment by dvanaken** [comment]
The output from OLTPBench is redirected to driver/oltp.log. What does it show?
