### ISSUE TITLE
The new config recommended have values outside the [min, max] range

### ISSUE THREAD

**Issue by niteshme2** [cmu-db/ottertune#325]
When trained on the trained data downloaded as per explained in the wiki and then running training loops, I get this error where it says that new config file contains error and that the values for a particular parameter are outside the valid range. I am attaching the screenshot.

PS. I am running it using dockerfiles
![image](https://user-images.githubusercontent.com/26631133/71660299-9786c380-2d70-11ea-9da5-732c21c172c6.png)

**Comment by dvanaken** [comment]
You can set the min/max range for each knob via the `edit knobs` button located on the main webpage for your session. Double-check these are set to appropriate values.
