### ISSUE TITLE
How to create knobs and metrics files under fixtures for a database

### ISSUE THREAD

**Issue by niteshme2** [cmu-db/ottertune#328]
For a specific database type and version there are two files in the fixtures folder in website. 
For ex:    for postgres 9.6 there are two files "postgres-96_knobs.json" and "postgres-96_metrics.json".

My question is how do I create these files for a new database?

**Comment by dvanaken** [comment]
Our scripts for creating the fixtures are located here: https://github.com/cmu-db/ottertune/tree/master/server/website/script/fixture_generators
