### ISSUE TITLE
Website loads the basic version. No styling is in effect

### ISSUE THREAD

**Issue by niteshme2** [cmu-db/ottertune#332]
When i run the website it looks like very basic html and seems that styling is not getting applied.
![image](https://user-images.githubusercontent.com/26631133/72076014-d7bee680-331a-11ea-8bd6-225cf673139a.png)

![image](https://user-images.githubusercontent.com/26631133/72076056-ec02e380-331a-11ea-99e7-ebd07ffdc655.png)

How can i correct this?

**Comment by dvanaken** [comment]
This happens if you run the website with `DEBUG=False` and have not set up the static files correctly. Please see the Django documentation: https://docs.djangoproject.com/en/3.0/howto/static-files/
