### ISSUE TITLE
Create A new Session-DBMS can't find the mysql option

### ISSUE THREAD

**Issue by gaochao-git** [cmu-db/ottertune#383]
i'm a MySQL DBA and want tune the MySQL ,but i can't find the option.

mysql> select * from website_dbmscatalog;
+-----+------+------------+
| id  | type | version    |
+-----+------+------------+
|   1 |    2 | 9.6        |
|   2 |    2 | 9.2        |
|   3 |    2 | 9.3        |
|   4 |    2 | 9.4        |
|   9 |    9 | 5.6        |
|  12 |    4 | 12.2.0.1.0 |
|  19 |    4 | 19.0.0.0.0 |
| 121 |    4 | 12.1.0.2.0 |
+-----+------+------------+

**Comment by gaochao-git** [comment]
thanks for your support!

**Comment by yangdsh** [comment]
I am sorry but Ottertune does not support tuning Mysql now. Supporting a new DBMS requires a lot of work, which we cannot afford now.

**Comment by bohanjason** [comment]
Actually we have mysql fixture in our private repo. Will put it in this public repo

**Comment by gaochao-git** [comment]
@bohanjason ，Thanks a lot !!!

**Comment by bohanjason** [comment]
reference: issue #401
