### ISSUE TITLE
Ease in adapting to TSDB DBMS?

### ISSUE THREAD

**Issue by remingtonc** [cmu-db/ottertune#4]
Currently MySQL, PostgreSQL, and Actian Vector are supported based on [the whitepaper](http://db.cs.cmu.edu/papers/2017/p1009-van-aken.pdf), can you theorize difficulty in application to TSDB tunings like [OpenTSDB](http://opentsdb.net), [InfluxDB](https://github.com/influxdata/influxdb), etc.?

**Comment by dvanaken** [comment]
OtterTune's optimization techniques are general and I think that it would be straightforward to support tuning TSDBs. During a tuning session, the only information that OtterTune collects from the DBMS is its current configuration and internal runtime metrics. We use [OLTPBench](https://github.com/oltpbenchmark/oltpbench.git) to automate the collection of this information as well as the benchmark/workload execution. If you can add support for the TSDB(s) that you are interested in tuning and (optionally) the benchmark(s) you want to tune to OLTPBench then you should be able to use OtterTune once we have the website is up and running.
