### ISSUE TITLE
Implement DS-DPPG (QTune algorithm)

### ISSUE THREAD

**Issue by mikefarmer01** [cmu-db/ottertune#412]
Hey guys,

I see you implemented the DPPG algorithm, that's nice.
Have you checked out QTune yet? In Guoliang Li et. al.'s paper "QTune: A Query-Aware Database Tuning System with Deep Reinforcement Learning - ), they suggest an algorithm they call dual-state DPPG, which they show to have further latency and throughput improvements over CDBTune (DPPG).

Have you thought about implementing this algorithm?

Link to the paper: https://doi.org/10.14778/3352063.3352129

**Comment by bohanjason** [comment]
It's not on our road map yet.
