### ISSUE TITLE
requirements.txt reference old tensorflow version

### ISSUE THREAD

**Issue by ToeiRei** [cmu-db/ottertune#423]
```
Could not find a version that satisfies the requirement tensorflow==1.12.2 (from -r ottertune/server/website/requirements.txt (line 24)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.12.2 (from -r ottertune/server/website/requirements.txt (line 24))
```

**Comment by dvanaken** [comment]
What Python version are you using? We support up to Python 3.6 and tensorflow 1.12.2 may not be available if you're running a newer version. You can try installing the package from the URL:
`pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.2-py3-none-any.whl`

But keep in mind you may run into more incompatibility issues if you're using Python >= 3.7.

**Comment by ToeiRei** [comment]
I guess that is the problem as debian busters default python version is 3.7 - I did not look at that as I was expecting debian to be a bit older.
