### ISSUE TITLE
Deployment Instructions?

### ISSUE THREAD

**Issue by madelinemacd** [cmu-db/ottertune#69]
I'm interested in trying out OtterTune, and I'd love more detailed information about where to start! I can see that most questions about deployment were closed last November with notes that more detailed instructions would be coming soon, is there an estimate on when more detailed information might be available, or any pointers on where to begin in the meantime?

**Comment by apavlo** [comment]
@madelinemacd This repository contains the new version of the system that makes it easier for other people to use. We are close to having the first release soon.

**Comment by madelinemacd** [comment]
@apavlo Great, thanks! I'll keep on checking back then

**Comment by chencheng1560** [comment]
@apavlo, Hi, I am trying to deploy the project, but meet several problems. May I know what is the version of java and python the project use?

**Comment by apavlo** [comment]
@chencheng1560 We're still working on the first release. It's not ready yet.

**Comment by chencheng1560** [comment]
@apavlo, thanks! really appreciate your work and looking forward to the new version

**Comment by KhangxLi** [comment]
@apavlo Hi, is the repo right now usable to tune a real database?

**Comment by bohanjason** [comment]
@KhangxLi  Yes. We use the repo to tune Postgres, and we improve the throughput from 400 (default) to 3000.

**Comment by nabti** [comment]
@bohanjason  Hello, thank you for your work. Can you please give me instructions on how to use Ottertune for mysql. 
I mean from the begining how to install it to how to use it. Need help please

Thank you
