### ISSUE TITLE
What's your plan about open source this project

### ISSUE THREAD

**Issue by zxsimple** [cmu-db/ottertune#7]
@dvanaken , it is so excited you make this project open source, according to the article [https://aws.amazon.com/cn/blogs/ai/tuning-your-dbms-automatically-with-machine-learning/](url) the OtterTune project consists of several module like Tuning Manager， JDBC Manager and so on. It seems the current release is incomplete, we can't run a complete scenario with OtterTunne and the Website project.
You also mentioned you will make it as online tuning service, so I wondering what's your plan about this project, will fully open source it or just part of it. If you will open source a 'work' release, what about the schedule?

Thanks.

**Comment by apavlo** [comment]
@zxsimple Thanks for your interest. We are working on tying together the different pieces and providing documentation on how to use the system. Everything will be posted here on Github.

**Comment by zxsimple** [comment]
Wonderful, looking forward the next release.

**Comment by yangminxingnus** [comment]
Hi, is this version complete now?
