### ISSUE TITLE
Port Ottertune to Python3

### ISSUE THREAD

**Issue by eribeiro** [cmu-db/ottertune#82]
As seen here: https://pythonclock.org/ , python2 is being retired in the next two years. It would be very handy to port it to python3 as soon as possible. One idea is to use `2to3` tool that allows for an automatic way of rewriting the source files of the project. It can be executed as a dry-run so that you can see the impact of the changes. The main impediment is that some libs like `poster` are not ported to python3 (one of the motivations to my PR https://github.com/cmu-db/ottertune/pull/49 , besides `requests` being awesome) , but this one in particular looks like abandonware, imho.

 Wdyt, @dvanaken ?

**Comment by apavlo** [comment]
@eribeiro Yes, we will eventually get to that. We are working on getting the system to run correctly first. Let's hold off on this for now.
