### ISSUE TITLE
upload_data.py not working

### ISSUE THREAD

**Issue by suafeng** [cmu-db/ottertune#83]
When I and Bohan tried to upload data using upload_data.py, we encountered following error.

> ubuntu@ubuntu-xenial:/ottertune/server/website$ python script/controller_simulator/upload_data.py script/controller_simulator/generated_data 0987654321
> Traceback (most recent call last):
>   File "script/controller_simulator/upload_data.py", line 64, in <module>
>     main()
>   File "script/controller_simulator/upload_data.py", line 60, in main
>     upload(args.datadir, args.upload_code)
>   File "script/controller_simulator/upload_data.py", line 30, in upload
>     for wkld_dir in sorted(glob.glob(os.path.join(basedir, '*'))):
>   File "/usr/lib/python2.7/posixpath.py", line 70, in join
>     elif path == '' or path.endswith('/'):
> AttributeError: 'list' object has no attribute 'endswith'

**Comment by suafeng** [comment]
created a pr to fix this, waiting for review

**Comment by dvanaken** [comment]
Fixed in #84
