### ISSUE TITLE
speed up the website

### ISSUE THREAD

**Issue by bohanjason** [cmu-db/ottertune#85]
The website is too slow when many results are uploaded. When uploading ~1000 results, the page response time is ~20 seconds. We need to speed up the website by optimizing Django code (e.g. use cache in Django). The response time can be reduced to less than 1 sec from my previous experience.

**Comment by swimj** [comment]
Hey, I think the issue might not be lack of caching.

Look at UpdateTask() class in tasks/async_tasks.py.  The rate_limit is currently set to '50/m'.  Is your 1000 result upload just a single upload (in which case rate_limit probably has nothing to do with the slowness), or many small uploads? If the latter, then maybe we just need to change the parameter?

Of course, caching is in itself a good thing anyway.

**Comment by bohanjason** [comment]
rate limiter affects the background tasks, which are asynchronous.  However, we need to do some optimizations to reduce page response time

**Comment by bohanjason** [comment]
Hi Tao, Siyuan, 

The main problem for now is that the view page will upload all results, which is very slow. To solve it, we can use Ajax to upload the results asynchronously, it can greatly improve the performance. I will finish it soon.

Also , there are some other optimizations we can do in Django. This[ link](https://docs.djangoproject.com/en/2.0/topics/db/optimization/) includes the details. For example, we can: 
1. Use index 
2. Retrieve everything at once
3. Use cache. 
etc. .. 

Could you please help optimize the website based on the the link above ? To get started, you may want to upload ~1000 results first, and you can see the response time is about 20 seconds. The Django debug tool is also a good thing to help you understand every part of the response time. You can use it directly in our website. 

Thanks ! 

Best,
Bohan

**Comment by bohanjason** [comment]
@suafeng  I have optimized session_view to speed up the website.  You may want to look into get_timeline_data in view.py. This function takes much time when loading the results.

**Comment by suafeng** [comment]
added prefetching in get_timeline_data.
